#!/bin/sh

cd /var/www

# 安全のためキャッシュクリア
php artisan config:clear || true
php artisan cache:clear || true

# キャッシュ再生成
php artisan config:cache
php artisan route:cache
php artisan view:cache

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf